services:
  navidrome:
    image: deluan/navidrome:latest
    user: "1002:1003" # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "https://navidrome.jwowk.net"
      ND_DATAFOLDER: "/data"
      ND_MUSICFOLDER: "/music"
      ND_SPOTIFY_ID: "b76094fd1a834c18906bea38977917ac"
      ND_SPOTIFY_SECRET: "51f57df3a2fa473991a87f000f1581cf"
    volumes:
      - "/docker/navidrome/data:/data"
      - "/mnt/storage_box/media/music:/music:ro"
    networks:
      - npm_net
networks:
  npm_net:
    external: true
